name: BuildAndTestOnEveryPush.yml

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build on windows-latest
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build
    
    - name: Test
      env:
        HIQ_AWSGATEWAY_URL:  ${{ secrets.HIQ_AWSGATEWAY_URL }}
        HIQ_AWSGATEWAY_ACCESSKEY:  ${{ secrets.HIQ_AWSGATEWAY_ACCESSKEY }}
        HIQ_AWSGATEWAY_SECRETKEY:  ${{ secrets.HIQ_AWSGATEWAY_SECRETKEY }}
        HIQ_AWSGATEWAY_SERVICENAME:  ${{ secrets.HIQ_AWSGATEWAY_SERVICENAME }}
        HIQ_AWSGATEWAY_REGION:  ${{ secrets.HIQ_AWSGATEWAY_REGION }}
      run: dotnet test
      
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push Frends.Community.AWS.Http\bin\Release\Frends.Community.AWS.Http.*.nupkg  --api-key ${{ secrets.COMMUNITY_FEED_API_KEY }} --source https://www.myget.org/F/frends-community-test/api/v2/package
